### ISSUE TITLE
Package manager installs

### ISSUE THREAD

**Issue by paul-hammant** [umlet/pwk#3]
```
pwk is a single-file app. Just download and chmod it, and you should be good to go.
```

Is insufficient. People want Homebrew style installs so they can keep up with your big fixes and enhancements.

**Comment by umlet** [comment]
Frankly, as this thing is not fully stable yet (and only out for about 18 hours), I'd like to wait a bit -- goal is to tweak it to its final capabilities, and then not to touch it again (so no need for continuous updates, let alone dep mgmt). Then: yes.

(On a personal note: not a huuuge fan of package managers here:
- they won't work for offline systems;
- each OS (worse: many tools and frameworks) seem to come with their own package manager nowadays (and not always transparent what gets installed where);
- new external (reverse) dependency on the packages manager (+1 dep, starting off with 0 deps for a single-file app).)

((Also, if useful, somewhere, someone will put it into a repo..))

**Comment by paul-hammant** [comment]
It might be sufficient for you write a subheading: Homebrew (Mac) and then "volunteers please" within that. That'd be in the homebrew repo, not yours, and it gets maintained by a larger part time crew after that.  Same for Choclately, apt, nix.

**Comment by umlet** [comment]
Repos stated as todos/goals.
